import React from 'react'

import Style from '../styles/index.module.css'
import { Herosection, Services, BigNFTSlider, Subscribe, Title } from '@/components/componentsindex'
const Home = () => {
  return (
    <div className='Style.Homepage'>
      <Herosection/>
      <Services/>
      <BigNFTSlider/>
      <Subscribe/>
      <Title
        heading="Browse by Category"
        paragraph="Browse the latest NFT's generated by AI"
      />
    </div>
  )
}

export default Home 